(function(_ds){var window=this;var pX=function(a){var b=a.Di;a=a.columns;let c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';const d=a.length;for(let e=0;e<d;e++){const f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.U(f.$m)+'" tabindex="0" track-type="nav" track-name="'+_ds.U(f.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.U(b)+'" track-metadata-module="secondary nav">'+_ds.R(f.text)+"</a></li>"}return(0,_ds.Q)(c+"</ul></div>")},qX=
function(a){var b=a.Di,c=a.href;a=a.text;return(0,_ds.Q)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.U(_ds.V(c))+'" track-type="nav" track-name="'+_ds.U(a)+'" track-metadata-eventdetail="'+_ds.U(c)+'" track-metadata-position="nav - '+_ds.U(b)+'" track-metadata-module="secondary nav">'+_ds.R(a)+"</a></div>")};var rX=function(a){a.o=Array.from(a.querySelectorAll("tab"));let b=a.querySelector(".devsite-tabs-wrapper");if(!b){b=a.ownerDocument.createElement("div");b.classList.add("devsite-tabs-wrapper");a.appendChild(b);var c;null==(c=a.o)||c.forEach(e=>{let f;return null==(f=b)?void 0:f.appendChild(e)})}a.v=b;a.appendChild(b);if(!a.hasAttribute("no-overflow")){c=a.ownerDocument.createElement("tab");_ds.F(a,"overflow-tab","",c);var d=a.ownerDocument.createElement("a");_ds.eh(d,"#");d.textContent="More";d.classList.add("devsite-icon");
d.classList.add("devsite-icon-arrow-drop-down");c.appendChild(d);a.g=c;d=a.ownerDocument.createElement("div");d.classList.add("devsite-tabs-overflow-menu");_ds.F(a,"scrollbars","",d);_ds.F(a,"hidden","",d);a.C=d;c.appendChild(d);b.appendChild(c)}},vX=function(a){let b;null==(b=a.o)||b.forEach(async(c,d)=>{if(await sX(c)){var e=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column")),f=c.querySelector(".devsite-tabs-dropdown"),g=c.querySelector("a");e.forEach((h,k)=>{_ds.F(a,"column-id",`tab-${d}-column-${k}`,
h)});e=e.map(h=>{const k=h.querySelector(".devsite-nav-title")||h.querySelector(".devsite-nav-item-title");return{$m:h.getAttribute("column-id"),text:null==k?void 0:k.textContent}});g&&(g=_ds.O(pX,{Di:(g.textContent||"").toLowerCase().trim(),columns:e}),f&&(e=c.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,e),f=c.querySelector(".dropdown-tabbed-menu a"),tX(c),a.eventHandler.listen(g,"click",h=>{h.preventDefault();const k=c.querySelector(".dropdown-tabbed-menu-button");h=h.target;
k&&h.tagName&&"a"===h.tagName.toLowerCase()&&!k.contains(h)&&uX(a,c,(null==h?void 0:h.getAttribute("column-id"))||"")}),f&&uX(a,c,f.getAttribute("column-id")||""))}})},wX=function(a,b){if(!b)return 0;const c=[];let d=b;for(;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.F(a,"render-hidden","",d),d=d.parentElement;a=_ds.Rk(b).width;for(const e of c)e.removeAttribute("render-hidden");return a},FX=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",()=>a.G.g());a.eventHandler.listen(a,
"click",c=>{if(!(c.shiftKey||c.ctrlKey||c.metaKey||c.altKey)){var d=c.target,e=xX(a,d);if(e)if(e===a.g)yX(a,c);else if(zX(a),d.classList.contains("devsite-tabs-dropdown-toggle"))c.preventDefault(),c.stopPropagation(),e.hasAttribute("dropdown--open")?AX(a):BX(a,e);else{var f;"A"===d.tagName?f=d:f=_ds.hi(d,"A");var g=e.querySelector(".devsite-tabs-dropdown");if(g&&g.contains(d))f&&f.hasAttribute("href")||(c.preventDefault(),c.stopPropagation());else{if(c=a.J||a.querySelector("[active]"))c.removeAttribute("active"),
_ds.F(a,"aria-selected","false",c);_ds.F(a,"active","",e);_ds.F(a,"aria-selected","true",e);a.J=e;f&&f&&"#"!==f.href||a.G.g()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover";const c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){for(const e of d)a.eventHandler.listen(e,"click",f=>{const g=f.target,h=xX(a,g),k=null==h?void 0:h.querySelector(".devsite-tabs-dropdown");
if(k){let l;(null==(l=a.g)?0:l.contains(g))||k.contains(g)||(f.preventDefault(),f.stopPropagation(),(null==h?0:h.hasAttribute("dropdown--open"))?AX(a):CX(a,f))}});a.eventHandler.listen(document.body,"click",e=>{a.v&&!a.v.contains(e.target)&&AX(a)})}else a.eventHandler.listen(a,b,e=>void DX(a,e)),a.eventHandler.listen(a,c,()=>void EX(a))}b=[...a.querySelectorAll(".devsite-tabs-close-button")];for(const c of b)a.eventHandler.listen(c,"click",()=>AX(a))},GX=function(a){_ds.F(a,"hidden","",a.g);if(!(a.o&&
3>a.o.length)){var b=wX(a,a);if(0!==b){var c,d=(null==(c=a.o)?void 0:c.slice())||[],e=0,f;d.forEach(k=>{k.parentNode!==a.v&&(f?f.parentNode&&f.parentNode.insertBefore(k,f.nextSibling):_ds.Qh(a.v,k,0));f=k;e+=wX(a,k)});if(!(e<=b)){c=a.H;var g;null==(g=a.g)||g.removeAttribute("hidden");(g=a.querySelector("[active]"))&&(c+=wX(a,g));for(var h;null==(h=d)?0:h.length;){const k=d.shift();if(k===g)continue;const l=wX(a,k||null);if(c+l<=b)c+=l;else{let m;null==(m=a.C)||m.appendChild(k)}}}}}},DX=async function(a,
b){(await _ds.x()).isTouchEnabled()||CX(a,b)},EX=async function(a){(await _ds.x()).isTouchEnabled()||AX(a,300)},AX=function(a,b=0){_ds.J(a.h);window.clearTimeout(a.D);const c=a.querySelector("tab[dropdown--open]");if(c){const d=c.querySelector(".devsite-tabs-dropdown");_ds.F(a,"dropdown-transition","",d);_ds.zk(a.h,d,_ds.gf,()=>{null==d||d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.F(a,"hidden","",d)});a.D=window.setTimeout(()=>{c.removeAttribute("dropdown--open");
HX(a,c)},b)}else a.removeAttribute("dropdown--open");zX(a)},xX=function(a,b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},CX=function(a,b){const c=b.target,d=xX(a,c);if(d){let e;d===a.g||(null==(e=a.g)?0:e.contains(c))?yX(a,b):BX(a,d)}},yX=async function(a,b){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));await _ds.jj();if(!a.hasAttribute("overflow-menu--open")){b=await _ds.x();await b.whenReady();
if(b.isTouchEnabled()){const d=e=>{a.contains(e.target)||zX(a);_ds.Ak(a.h,document.body,["devsite-close-overflow-tabs","click"],d)};a.h.listen(document.body,["devsite-close-overflow-tabs","click"],d)}var c;null==(c=a.C)||c.removeAttribute("hidden");_ds.F(a,"overflow-menu--open","")}},BX=async function(a,b){zX(a);if(b.hasAttribute("dropdown")){if(_ds.J(a.h),window.clearTimeout(a.D),!b.hasAttribute("dropdown--open")){(await _ds.x()).isTouchEnabled()&&_ds.zk(a.h,document.body,"click",g=>{a.contains(g.target)||
AX(a)});var c=a.querySelector("tab[dropdown--open]"),d=b.querySelector(".devsite-tabs-dropdown");if(d){d.removeAttribute("hidden");_ds.Fk(d,"left","");var e=_ds.Hh(window||window),f=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&1<f.length){const g=[];f.forEach(k=>{g.push(k.scrollWidth)});const h=Math.max.apply(null,g);h*f.length<e.width?f.forEach(k=>{_ds.Fk(k,"width",`${h}px`)}):_ds.F(a,"dropdown-full","",b)}f=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?
_ds.Fk(d,"left",`-${f.left}px`):(e=Math.min(f.left,f.left+f.width-e.width),0<e&&_ds.Fk(d,"left",`-${e}px`));c?(c.removeAttribute("dropdown--open"),HX(a,c),c=c.querySelector(".devsite-tabs-dropdown"),null==c||c.removeAttribute("dropdown-transition"),_ds.F(a,"hidden","",c)):(_ds.F(a,"dropdown-transition","",d),_ds.zk(a.h,d,_ds.gf,()=>d.removeAttribute("dropdown-transition")));window.requestAnimationFrame(()=>{_ds.F(a,"dropdown--open","");_ds.F(a,"dropdown--open","",b);HX(a,b)})}else c&&(c.removeAttribute("dropdown--open"),
HX(a,c))}}else AX(a)},HX=function(a,b){_ds.F(a,"aria-expanded",`${b.hasAttribute("dropdown--open")}`,b.querySelector(".devsite-tabs-dropdown-toggle"))},zX=function(a){_ds.F(a,"hidden","",a.C);a.removeAttribute("overflow-menu--open")},sX=async function(a){return(await _ds.x()).isTouchEnabled()||!a.hasAttribute("generated-tab-menu")?!1:!0},tX=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&
(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.O(qX,{Di:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null==a||a.appendChild(c)))}},uX=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(e=>e.removeAttribute("active"));d.forEach(e=>_ds.F(a,"hidden","",e));b=b.find(e=>e.getAttribute("column-id")===
c);d=d.find(e=>e.getAttribute("column-id")===c);b&&d&&(_ds.F(a,"active","",b),d.removeAttribute("hidden"))},IX=class extends _ds.G{constructor(){super();this.eventHandler=new _ds.I;this.h=new _ds.I;this.G=new _ds.vk(()=>{GX(this)},20);this.J=null;this.F=!1;this.D=0;this.C=this.g=null;this.H=0;this.o=[];this.v=null;_ds.Og(this,this.j`active`,this.j`aria-expanded`,this.j`aria-selected`,this.j`collapsed`,this.j`column-id`,this.j`connected`,this.j`dropdown`,this.j`dropdown-full`,this.j`dropdown--open`,
this.j`dropdown-transition`,this.j`hidden`,this.j`no-overflow`,this.j`overflow-menu--open`,this.j`overflow-tab`,this.j`render-hidden`,this.j`scrollbars`)}disconnectedCallback(){_ds.J(this.eventHandler);_ds.J(this.h)}connectedCallback(){this.F||(rX(this),this.F=!0);_ds.F(this,"connected","");if(!this.hasAttribute("no-overflow")){_ds.F(this,"collapsed","",this.g);this.H=wX(this,this.g);var a;null==(a=this.g)||a.removeAttribute("collapsed");FX(this);GX(this)}vX(this)}};
IX.prototype.connectedCallback=IX.prototype.connectedCallback;IX.prototype.disconnectedCallback=IX.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",IX)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
