(function(_ds){var window=this;var gN=function(a){return!a.classList.contains("material-icons")},oN=async function(a,b){await DevsiteApp.whenReady();const c=_ds.H();var d=DevsiteApp.getInsecureHost();b=b.X;if(b.origin===c.origin||!d||b.origin===d){try{var e=_ds.Se(_ds.yl,b.data)}catch(g){return}d=_ds.ze(e,1,0);if(4===d)hN(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:iN(e,f);break;case 8:jN(b,e,c);break;case 1:kN(b,e,c);break;case 6:case 7:lN(d,c,e);break;case 9:mN(a,
e);break;case 10:nN(e,c)}}}},sN=function(a){a.o=a.querySelector(".devsite-article-body");a.o&&(pN(a),a.v=[]);a.g&&a.g.disconnect();a.h.clear();qN(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.o&&(b=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.h.clear();a.h=new Set(c);if(_ds.H().hash){c=new _ds.AF;for(const d of a.h)_ds.zF(c,d,gN)}else rN(a,a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},qN=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));b.parentNode&&b.parentNode.insertBefore(c,b);c.appendChild(b)}})},hN=async function(a,b){const c=tN(a,b.source);if(c){const e="goog_"+_ds.xh++;c.setAttribute("name",e);var d=_ds.zl(3);d=_ds.Qe(d,2,e);(b=b.source)&&b.postMessage(_ds.Te(d),"*");(b=document.body.getAttribute("appearance"))&&uN(c,b);a.v.push(c)}},iN=async function(a,b){const c=_ds.Jh(document).y,d=_ds.Le(a,4);a=_ds.Le(a,
3);b=_ds.Xh(b);d&&b.setAttribute("width",`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.Jh(document).x,c)})},jN=async function(a,b,c){b=_ds.Al(_ds.zl(8),_ds.z(b,8));c=_ds.Qe(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.Te(c),"*")},kN=async function(a,b,c){b=_ds.Al(_ds.zl(2),_ds.z(b,8));c=_ds.Qe(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.Te(c),"*")},lN=async function(a,b,c){const d=c.Ia();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},mN=async function(a,b){const c=_ds.z(b,9);b=JSON.parse(_ds.z(b,10));"cloudtrackEvent"===c&&b?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:b},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:b,bubbles:!0}))},nN=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===
c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},tN=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Yh(d)===b&&(c=d)});return c},uN=function(a,b){var c=_ds.zl(12);b=_ds.Qe(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.Te(b),"*")},pN=function(a){"full"===document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},rN=function(a,b){a.g&&b.forEach(c=>{a.g.observe(c)})},vN=class extends _ds.G{constructor(){super();this.C=new _ds.I;this.D=new _ds.I;this.h=new Set;this.v=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&(a=b.target,_ds.zF(new _ds.AF,a,gN),this.h.delete(a),this.g.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.C.listen(window,"message",a=>oN(this,a));this.C.listen(document.body,
"devsite-appearance-updated",a=>{if((a=a.X.detail.wb)&&this.v.length)for(const b of this.v)uN(b,a)});sN(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.J(this.C);_ds.J(this.D)}fb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>{_ds.Rg(this,this.querySelector(b),a.querySelector(b))}),sN(this))}};vN.prototype.updateContent=vN.prototype.fb;vN.prototype.disconnectedCallback=vN.prototype.disconnectedCallback;
vN.prototype.connectedCallback=vN.prototype.connectedCallback;try{window.customElements.define("devsite-content",vN)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
