(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var TP=_ds.ah(function(){return!_ds.Qd||0<=_ds.Na(_ds.XH,9)}),UP=_ds.ah(function(){return _ds.Ud||_ds.Rd||_ds.Td&&0<=_ds.Na(_ds.XH,10)||_ds.Qd&&0<=_ds.Na(_ds.XH,10)}),WP=function(a,b){TP()&&(b=UP()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Fk(a,VP(),b))},VP=_ds.ah(function(){return _ds.Qd&&9==_ds.le?"-ms-transform":"transform"});var ZP=function(a){a.h=XP(a,".devsite-top-logo-row-wrapper-wrapper");a.g=XP(a,".devsite-collapsible-section");a.o=XP(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);YP(a)},YP=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.F&&(_ds.Fk(b,"transform",`translate3d(0, -${a.offset}px, 0)`),$P(a),a.F=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},aQ=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.J(a.D);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.nh(b.offsetWidth,b.offsetHeight);b=new _ds.nh(c.offsetWidth,c.offsetHeight);var f=_ds.Yk(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Fk(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});WP(c,a.hasAttribute("search-active")?0:e);_ds.zk(a.D,d,_ds.gf,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),WP(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.C=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(TP()){var m=UP()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.Fk(d,VP(),m)}WP(c,k)})}},bQ=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.jj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},dQ=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.X;_ds.hi(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>cQ(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{cQ(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},eQ=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},$P=function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},cQ=function(a){window.requestAnimationFrame(()=>
a.J.g())},XP=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},fQ=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},gQ=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Rg(a,c,b))},hQ=class extends _ds.G{constructor(){super(...arguments);this.eventHandler=new _ds.I;this.F=
-1;this.D=new _ds.I;this.C=0;this.G=new MutationObserver(()=>ZP(this));this.J=new _ds.vk(()=>{ZP(this);$P(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;YP(this);break;case "search-active":aQ(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),bQ(this,a)}}connectedCallback(){dQ(this);eQ(this);$P(this);ZP(this);this.G.observe(this,{childList:!0,subtree:!0});YP(this);const a=_ds.H();this.authUser=_ds.Li(_ds.Mi(a.href),"authuser")}disconnectedCallback(){_ds.J(this.eventHandler);this.G.disconnect()}v(){return this.h+this.g-this.offset}H(){return this.h+this.g}fb(a){this.updated=!1;if(a){gQ(this,a,".devsite-header-upper-tabs");
gQ(this,a,".devsite-collapsible-section");gQ(this,a,".devsite-product-name-wrapper");gQ(this,a,"devsite-language-selector");gQ(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&fQ(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(fQ(c,b),c=_ds.H(),c=_ds.Li(_ds.Mi(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Rg(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Rg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Ph(this),this.appendChild(a));eQ(this);cQ(this)}};try{window.customElements.define("devsite-header",hQ)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
