(function(_ds){var window=this;var eL=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},fL=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')},gL=function(a){var b=a.Eo;a='<span class="devsite-nav-filter-match-count"> (<mark>';b=_ds.mF(new _ds.hF("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:b,XXX_1:_ds.R(_ds.aq(1,_ds.$E[void 0]||
1)),XXX_2:_ds.R(_ds.aq(b,_ds.$E[void 0]||1))});return(0,_ds.Q)(a+b+"</mark>)</span>")};var hL="onpointerover"in window?"pointerover":"mouseover",iL=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.F(a,"visually-hidden","",c))},qL=function(a){a.eventHandler.listen(a,"click",b=>void jL(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&jL(a,b)});a.eventHandler.listen(a,[hL,"focusin"],b=>void kL(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.o&&(lL(a,"_book")?a.removeAttribute("top-level-nav"):_ds.F(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.K.g());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.K.g()});a.eventHandler.listen(a,"scroll",()=>{_ds.F(a,"user-scrolled","")});a.eventHandler.listen(a.g,"click",()=>{mL(a)});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.L.g()),a.eventHandler.listen(a.h,"focus",()=>void nL(a,"focus")));a.F&&a.eventHandler.listen(a.F,"click",
()=>{a.h&&(a.h.value="",a.h.focus());let b;null==(b=a.F)||b.classList.add("hidden");oL(a);pL(a);nL(a,"click")})},sL=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.D=new Set(b);if(!_ds.H().hash&&c)rL(a,a.D);else{c=new _ds.AF;for(const d of a.D)_ds.zF(c,d)}},tL=async function(a){const b=await _ds.x();for(const c of a.D)b.unregisterIntersectionForElement(c)},jL=function(a,b){if(!b.defaultPrevented){var c=b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),
b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.F(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&lL(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?
0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.F(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},kL=function(a,b){b.defaultPrevented||(b=_ds.gi(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ec(b,_ds.Sc(_ds.cj(b.href).href)))},mL=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;
_ds.zk(a.eventHandler,a,_ds.gf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.v.removeAttribute("animatable")});_ds.F(a,"animatable","");b=_ds.Hc(a.j`animatable`);b(a.background,"animatable","");b(a.v,"animatable","");a.hasAttribute("collapsed")?(_ds.F(a,"aria-expanded","true",a.g),_ds.F(a,"aria-label","Hide side navigation",a.g),_ds.F(a,"data-title","Hide side navigation",a.g),a.removeAttribute("collapsed"),uL(a,"Expanded book nav")):(a.g.removeAttribute("aria-expanded"),
_ds.F(a,"aria-label","Show side navigation",a.g),_ds.F(a,"data-title","Show side navigation",a.g),_ds.F(a,"collapsed",""),uL(a,"Collapsed book nav"));await _ds.jj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},nL=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},
bubbles:!0}))},vL=function(a){a.J=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},xL=function(a){const b=_ds.H().searchParams.get("nf");a.h&&b&&(a.h.value=b,wL(a))},wL=function(a){if(a.J.length){oL(a);pL(a);var b,c,d=null==(b=a.h)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.F)||e.classList.remove("hidden");for(const g of a.J){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");
var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&
(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Fc(f,_ds.Gg.g(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.O(gL,{Eo:a}),b.appendChild(a))}}else null==(f=a.F)||f.classList.add("hidden")}},oL=function(a){for(const b of a.J){let c;b.classList.toggle("hidden",!(null==(c=a.h)||!c.value))}},pL=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();
a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Fc(a,_ds.Gg.g(b))}}},rL=async function(a,b){if(a.C){var c=await _ds.x(),d=new _ds.AF,e=f=>{f=f.target;_ds.zF(d,f);a.D.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},lL=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),
c=!0):_ds.F(a,"hidden","",d);return c},yL=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.pj(_ds.H().pathname);a=`[href="${_ds.cj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},zL=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},BL=async function(a){a.C&&(a.removeAttribute("user-scrolled"),await _ds.jj(),await AL(a),await a.R,await _ds.x(),await _ds.jj(),await AL(a))},
AL=async function(a){if(a.C&&a.o){await _ds.x();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await CL(a,b))}},CL=async function(a,b){if(a.C){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Pk(b,a,!0).y;await _ds.jj();c&&_ds.F(a,"user-scrolled","")}},uL=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},DL=class extends _ds.G{constructor(){super();
this.C=!1;this.F=this.h=this.G=this.o=null;this.J=[];this.eventHandler=new _ds.I;this.N=()=>{};this.D=new Set;this.H=this.M=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.g=_ds.O(eL);this.v=_ds.O(fL);this.R=new Promise(a=>{this.N=a});this.K=new _ds.vk(()=>{this.C&&iL(this)},20);this.L=new _ds.vk(()=>{wL(this)},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){this.C=!0;_ds.Og(this,this.j`animatable`,
this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);this.parentNode&&this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.F(this,"hidden","",this.g),_ds.F(this,"hidden","",this.v));const a=await _ds.x();if(this.M=a.hasFlagAccess(150)){let b;null==(b=this.parentElement)||b.insertBefore(this.g,this.nextSibling);_ds.F(this,"aria-label",
"Hide side navigation",this.g);_ds.F(this,"data-title","Hide side navigation",this.g);_ds.F(this,"aria-expanded","true",this.g);let c;null==(c=this.parentElement)||c.insertBefore(this.v,this.nextSibling)}if(this.H=a.hasFlagAccess(155))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.h=this.G.querySelector("input[type=text]"),this.F=this.G.querySelector(".filter-clear-button"),vL(this),xL(this);iL(this);qL(this);await this.init();sL(this)}disconnectedCallback(){this.C=!1;_ds.J(this.eventHandler);
tL(this);this.D.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.F(this,"visually-hidden","",a);a=[this.background,this.g,this.v];for(const b of a)b&&_ds.Rh(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.v.removeAttribute("animatable");this.v.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",
{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.F(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.g,this.v];for(const d of c)d&&(b?_ds.F(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.N()}async init(a=!0){if(this.C){this.v.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.F(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.F(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.F(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(yL(this),zL(this),await BL(this)):(await _ds.jj(),await AL(this))}}async fb(a){a?(a=a.querySelector("nav")||
null,yL(this,a),zL(this,a),a&&(await tL(this),this.D.clear(),sL(this,a,!1)),_ds.Rg(this,this.querySelector("nav"),a)):_ds.Ph(this);if(this.H&&(vL(this),this.h)){this.h.value="";let b;null==(b=this.F)||b.classList.add("hidden");xL(this)}await _ds.jj();await this.init(!1)}};DL.prototype.updateContent=DL.prototype.fb;DL.prototype.attributeChangedCallback=DL.prototype.attributeChangedCallback;DL.prototype.disconnectedCallback=DL.prototype.disconnectedCallback;DL.prototype.connectedCallback=DL.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",DL)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
