(function(_ds){var window=this;var fY=function(a){var b=a.Dp,c=a.Zb,d=a.cn;a=a.jo;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.Ay("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=b[h];e+='<li class="devsite-nav-item"'+
(c&&g.index<a?" visible":"")+'><a href="#'+_ds.U(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+'" track-metadata-link-destination="#'+_ds.U(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(g.text)+"</span></a>";if(_ds.S(g.children).length){e+='<ul class="devsite-nav-list">';
g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.U(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+"."+_ds.U(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+"."+_ds.U(l)+'" track-metadata-link-destination="#'+
_ds.U(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.R(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.Ay("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.Q)(e+"</ul>")};var hY=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Zb?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),gY(a,b),a.F=!0):a.Ja()}},jY=async function(a){await iY(a);if(a.g){var b=`#${a.g.id}`,c=encodeURI(b);b=a.D.get(b)||a.D.get(c);a.o!==b&&(a.o&&a.o.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.o=b))}},kY=function(a){a.Zb||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
()=>{a.K.g()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{hY(a)})},lY=async function(a){if("IntersectionObserver"in _ds.Kh()){a.v&&a.v.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await window.customElements.whenDefined("devsite-header"),(b=Number(b.getAttribute("top-row--height"))+Number(b.getAttribute("bottom-row--height")))&&(c=b));a.v=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.C.add(e.target):a.C.delete(e.target);a.K.g()},
{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.H.g()},iY=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),b=c.v());c=a.h.findIndex(e=>a.C.has(e)&&e.getBoundingClientRect().top>=b);const d=a.h[c];if(d){const e=await mY();d.getBoundingClientRect().top-b>e&&0<c?a.g=a.h[c-1]:a.g=d}else a.g&&a.g.getBoundingClientRect().top>window.innerHeight&&(c=a.h.indexOf(a.g),0<c&&(a.g=a.h[c-1]))},gY=function(a,b){const c=[];
let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.h=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>nY(f));for(const [f,g]of a.h.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-
1].children.push(b):c.push(b);_ds.eb(a.G,c,a.J.bind(a))&&a.F||(c.length?(oY(a,c),a.show(),a.Zb||pY(a)):a.Ja(),a.G=c)},nY=function(a){return _ds.uj.find(b=>!!_ds.hi(a,null,b,6))||_ds.hi(a,"devsite-selector",null,6)||_ds.hi(a,null,"devsite-dialog",3)?!1:!0},oY=function(a,b){const c=_ds.O(fY,{Dp:b,Zb:a.Zb,cn:!!document.body.querySelector("devsite-apix, .devsite-apix"),jo:8>b.length?8:5});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.D.set(e,b);
a.D.set(f,b)}_ds.Ph(a);a.Zb&&_ds.F(a,"hidden","",c);a.appendChild(c);if(a.Zb){if(8<a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.F(a,"expanded","")});_ds.F(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},0)}},pY=async function(a){await a.H.promise;if(a.v){a.v.disconnect();
a.C.clear();a.o&&a.o.classList.remove("devsite-nav-active");a.o=null;for(const b of a.h)a.v.observe(b)}},mY=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),a=c.v(),b=c.H());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},qY=class extends _ds.G{constructor(){super();this.eventHandler=new _ds.I;this.H=new _ds.Bk;this.C=new Set;this.D=new Map;this.N=new _ds.vk(()=>void hY(this),16);this.K=new _ds.vk(()=>
void jY(this),33);this.g=this.o=null;this.h=[];this.F=!1;this.v=null;this.Zb=!1;this.G=[];_ds.Og(this,(0,_ds.u)`disabled`,(0,_ds.u)`has-sidebar`,(0,_ds.u)`hidden`,(0,_ds.u)`expandable`,(0,_ds.u)`expanded`,(0,_ds.u)`visible`)}static get observedAttributes(){return["max-height","offset"]}connectedCallback(){this.Zb=this.hasAttribute("devsite-toc-embedded");hY(this);kY(this)}disconnectedCallback(){this.Ja();this.F=!1;_ds.J(this.eventHandler)}Bf(a){a=a&&"false"===a.toLowerCase();this.G=[];_ds.Ph(this);
a?(_ds.F(this,"disabled",""),this.Ja()):(this.removeAttribute("disabled"),this.show(),this.N.g())}Ja(){_ds.Ph(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.F(this,"hidden","");if(!this.Zb){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.F(this,"visible","");if(!this.Zb){const a=
document.querySelector(".devsite-main-content");a&&_ds.F(this,"has-sidebar","",a);lY(this)}}J(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.eb(a.children,b.children,this.J.bind(this));return c&&a.id===b.id&&a.text===b.text}};qY.prototype.renderUpdatedContent=qY.prototype.Bf;qY.prototype.disconnectedCallback=qY.prototype.disconnectedCallback;qY.prototype.connectedCallback=qY.prototype.connectedCallback;try{window.customElements.define("devsite-toc",qY)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
