(function(_ds){var window=this;var vR=_ds.xC(['button:after,button:before{-moz-osx-font-smoothing:grayscale;text-rendering:optimizeLegibility;text-transform:none;word-wrap:normal;color:var(--devsite-secondary-text-color)}:host{display:block;position:relative}*{-moz-box-sizing:border-box;box-sizing:border-box}[hidden]{display:none}button{-moz-appearance:none;-webkit-appearance:none;-webkit-box-align:center;-webkit-align-items:center;-moz-box-align:center;-ms-flex-align:center;align-items:center;background-color:var(--devsite-select-background-color);border:var(--devsite-select-border,var(--devsite-secondary-border));border-radius:var(--devsite-select-border-radius);box-shadow:none;color:var(--devsite-select-color,var(--devsite-primary-text-color));cursor:pointer;display:-webkit-box;display:-webkit-flex;display:-moz-box;display:-ms-flexbox;display:flex;font:var(--devsite-select-font,500 14px/36px var(--devsite-primary-font-family));height:36px;max-width:154px;outline:0;padding-block:0;padding-inline:11px 7px;-webkit-transition:background-color .2s;transition:background-color .2s}button:is(:hover,:focus){background:var(--devsite-select-background-color-hover,var(--devsite-background-3))}button:before{font:24px/1 Material Icons;-webkit-font-feature-settings:"liga";-moz-font-feature-settings:"liga";font-feature-settings:"liga";-webkit-font-smoothing:antialiased;content:"language";margin-inline:0 8px}button:after{font:24px/1 Material Icons;-webkit-font-feature-settings:"liga";-moz-font-feature-settings:"liga";font-feature-settings:"liga";-webkit-font-smoothing:antialiased;content:"arrow_drop_down"}button>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}[role=dialog]{background:var(--devsite-background-1);border:var(--devsite-list-border,var(--devsite-secondary-border));border-radius:var(--devsite-list-border-radius,2px);box-shadow:0 1px 2px 0 var(--devsite-elevation-key-shadow-color),0 2px 6px 2px var(--devsite-elevation-ambient-shadow-color);left:var(--devsite-language-selector-menu-left);max-height:304px;overflow:hidden auto;padding:8px 0;position:absolute;right:var(--devsite-language-selector-menu-right);top:36px;-webkit-transform:var(--devsite-language-selector-menu-transform);transform:var(--devsite-language-selector-menu-transform);z-index:1}']);var wR=async function(a){if(!a.g.get("django_language")){const b=await _ds.x();a.g.set("django_language",b.getLocale()||"en",{Nb:15552E3,path:"/"})}},xR=async function(a){const b=a.g.get("django_language");b&&await a.T.set("language_preference",b)},yR=function(a){a.eventHandler.listen(document.body,"click",b=>{b.target!==a&&(a.open=!1,_ds.J(a.eventHandler))});a.eventHandler.listen(document.body,"keydown",async b=>{"Escape"===b.key&&(a.open=!1,_ds.J(a.eventHandler),a.toggle.focus())})},zR=async function(a,
b,c){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Language Selector",action:`${b} to ${c}`},bubbles:!0}));b={eventData:JSON.stringify({name:"change",type:"languageSelector",metadata:{"selected-language":`${c}`,"original-language":`${b}`}})};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:b,bubbles:!0}))},AR=async function(a,b){const c=b.target.getAttribute("lang");c&&(b.stopPropagation(),await _ds.x(),
a.g.remove("django_language"),a.g.set("django_language",c,{Nb:15552E3,path:"/"}),(b=document.documentElement.getAttribute("lang"))&&await zR(a,b,c),await xR(a),a=new URL(_ds.Kh().location.toString()),a.searchParams.delete("hl"),a=_ds.Sc(a.toString()),_ds.Kh().location.assign(_ds.Dc(a)))},BR=class extends _ds.UC{constructor(){super(...arguments);this.g=new _ds.Oq;this.eventHandler=new _ds.I;this.F=[];this.J=0;this.T=_ds.pl();this.pc="English";this.open=!1}static get g(){return vR}async connectedCallback(){super.connectedCallback();
try{await wR(this),await xR(this)}catch(a){}}h(){this.F=[...this.querySelectorAll("a")];this.J=this.F.length-1;let a;const b=null==(a=this.querySelector("[aria-current]"))?void 0:a.textContent;b&&(this.pc=b)}async L(){if(this.open=!this.open){await this.H;let a;null==(a=this.querySelector("[aria-current]"))||a.focus();yR(this)}else _ds.J(this.eventHandler)}render(){return(0,_ds.W)`
      <button type="button"
              aria-controls="language-menu"
              aria-haspopup="true"
              aria-label="${"Select your language preference."}"
              @click="${this.L}">
        <span>${this.pc}</span>
      </button>
      <div id="language-menu"
           role="dialog"
           @click="${a=>void AR(this,a)}"
           @keydown="${a=>{if("ArrowUp"===a.key||"ArrowDown"===a.key){a.preventDefault();let b=0;const c=document.activeElement;c&&(b=this.F.indexOf(c));b="ArrowUp"===a.key?0===b?this.J:b-1:b===this.J?0:b+1;this.F[b].focus()}}}"
           ?hidden=${!this.open}>
        <slot></slot>
      </div>`}fb(a){if(a&&(a=a.querySelector("ul"))){let b;null==(b=this.querySelector("ul"))||b.remove();this.append(a);_ds.JC(this)}}};_ds.A([_ds.cp(),_ds.B(Object)],BR.prototype,"pc",void 0);_ds.A([_ds.cp(),_ds.B(Object)],BR.prototype,"open",void 0);_ds.A([_ds.bp("button"),_ds.B(HTMLButtonElement)],BR.prototype,"toggle",void 0);try{window.customElements.define("devsite-language-selector",BR)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
