(function(_ds){var window=this;var OM=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.Ay("Action buttons");return(0,_ds.Q)(a+'"></div>')},PM=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.U(a)+'" data-title="'+_ds.U(a)+'"></button>')},QM=function(a){a=
a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.U(a)+'" data-title="'+_ds.U(a)+'"></button>')},RM=function(a){var b=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.U(a.dn)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.U(b)+'" data-title="'+_ds.U(b)+'"></button>')},SM=function(a){a=a.label;return(0,_ds.Q)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.U(a)+'" data-title="'+_ds.U(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(L){return L.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;")}function b(L,X,la){switch(L.nodeType){case 1:var ia=L.tagName.toLowerCase();X.push("<",ia);var ta=L.attributes,Qa=ta.length;if(Qa){if(la){for(var Fa=[],wa=Qa;0<=--wa;)Fa[wa]=ta[wa];Fa.sort(function(ua,La){return ua.name<La.name?-1:ua.name===La.name?0:1});ta=Fa}for(wa=0;wa<Qa;++wa)Fa=ta[wa],Fa.specified&&X.push(" ",Fa.name.toLowerCase(),'="',Fa.value.replace(t,"&amp;").replace(v,"&lt;").replace(w,"&gt;").replace(y,
"&quot;"),'"')}X.push(">");for(ta=L.firstChild;ta;ta=ta.nextSibling)b(ta,X,la);!L.firstChild&&/^(?:br|link|img)$/.test(ia)||X.push("</",ia,">");break;case 3:case 4:X.push(a(L.nodeValue))}}function c(L){function X(Z){if("\\"!==Z.charAt(0))return Z.charCodeAt(0);switch(Z.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(Z.substring(2),16)||Z.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(Z.substring(1),
8);default:return Z.charCodeAt(1)}}function la(Z){if(32>Z)return(16>Z?"\\x0":"\\x")+Z.toString(16);Z=String.fromCharCode(Z);if("\\"===Z||"-"===Z||"["===Z||"]"===Z)Z="\\"+Z;return Z}function ia(Z){var aa=Z.substring(1,Z.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));Z=[];for(var Y=[],Ba="^"===aa[0],ca=Ba?1:0,xa=aa.length;ca<xa;++ca){var ja=aa[ca];switch(ja){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":Z.push(ja);
continue}ja=X(ja);if(ca+2<xa&&"-"===aa[ca+1]){var Sa=X(aa[ca+2]);ca+=2}else Sa=ja;Y.push([ja,Sa]);65>Sa||122<ja||(65>Sa||90<ja||Y.push([Math.max(65,ja)|32,Math.min(Sa,90)|32]),97>Sa||122<ja||Y.push([Math.max(97,ja)&-33,Math.min(Sa,122)&-33]))}Y.sort(function(Sb,Od){return Sb[0]-Od[0]||Od[1]-Sb[1]});aa=[];ja=[NaN,NaN];for(ca=0;ca<Y.length;++ca)xa=Y[ca],xa[0]<=ja[1]+1?ja[1]=Math.max(ja[1],xa[1]):aa.push(ja=xa);Y=["["];Ba&&Y.push("^");Y.push.apply(Y,Z);for(ca=0;ca<aa.length;++ca)xa=aa[ca],Y.push(la(xa[0])),
xa[1]>xa[0]&&(xa[1]+1>xa[0]&&Y.push("-"),Y.push(la(xa[1])));Y.push("]");return Y.join("")}function ta(Z){for(var aa=Z.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),Y=aa.length,Ba=[],ca=0,xa=0;ca<Y;++ca){var ja=aa[ca];"("===ja?++xa:"\\"===ja.charAt(0)&&(ja=+ja.substring(1))&&ja<=xa&&(Ba[ja]=-1)}for(ca=1;ca<Ba.length;++ca)-1===Ba[ca]&&(Ba[ca]=++Qa);for(xa=ca=0;ca<Y;++ca)ja=
aa[ca],"("===ja?(++xa,void 0===Ba[xa]&&(aa[ca]="(?:")):"\\"===ja.charAt(0)&&(ja=+ja.substring(1))&&ja<=xa&&(aa[ca]="\\"+Ba[xa]);for(xa=ca=0;ca<Y;++ca)"^"===aa[ca]&&"^"!==aa[ca+1]&&(aa[ca]="");if(Z.ignoreCase&&Fa)for(ca=0;ca<Y;++ca)ja=aa[ca],Z=ja.charAt(0),2<=ja.length&&"["===Z?aa[ca]=ia(ja):"\\"!==Z&&(aa[ca]=ja.replace(/[a-zA-Z]/g,function(Sa){Sa=Sa.charCodeAt(0);return"["+String.fromCharCode(Sa&-33,Sa|32)+"]"}));return aa.join("")}for(var Qa=0,Fa=!1,wa=!1,ua=0,La=L.length;ua<La;++ua){var Ma=L[ua];
if(Ma.ignoreCase)wa=!0;else if(/[a-z]/i.test(Ma.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Fa=!0;wa=!1;break}}var Da=[];ua=0;for(La=L.length;ua<La;++ua){Ma=L[ua];if(Ma.global||Ma.multiline)throw Error(""+Ma);Da.push("(?:"+ta(Ma)+")")}return new RegExp(Da.join("|"),wa?"gi":"g")}function d(L){var X=0;return function(la){for(var ia=null,ta=0,Qa=0,Fa=la.length;Qa<Fa;++Qa)switch(la.charAt(Qa)){case "\t":ia||(ia=[]);ia.push(la.substring(ta,Qa));ta=L-X%L;for(X+=ta;0<=ta;ta-=16)ia.push("                ".substring(0,
ta));ta=Qa+1;break;case "\n":X=0;break;default:++X}if(!ia)return la;ia.push(la.substring(ta));return ia.join("")}}function e(L,X,la,ia){X&&(L={source:X,tj:L},la(L),ia.push.apply(ia,L.Ej))}function f(L,X){var la={},ia;(function(){for(var Fa=L.concat(X),wa=[],ua={},La=0,Ma=Fa.length;La<Ma;++La){var Da=Fa[La],Z=Da[3];if(Z)for(var aa=Z.length;0<=--aa;)la[Z.charAt(aa)]=Da;Da=Da[1];Z=""+Da;ua.hasOwnProperty(Z)||(wa.push(Da),ua[Z]=null)}wa.push(/[\0-\uffff]/);ia=c(wa)})();var ta=X.length,Qa=function(Fa){for(var wa=
Fa.tj,ua=[wa,"pln"],La=0,Ma=Fa.source.match(ia)||[],Da={},Z=0,aa=Ma.length;Z<aa;++Z){var Y=Ma[Z],Ba=Da[Y],ca=void 0;if("string"===typeof Ba)var xa=!1;else{var ja=la[Y.charAt(0)];if(ja)ca=Y.match(ja[1]),Ba=ja[0];else{for(xa=0;xa<ta;++xa)if(ja=X[xa],ca=Y.match(ja[1])){Ba=ja[0];break}ca||(Ba="pln")}!(xa=5<=Ba.length&&"lang-"===Ba.substring(0,5))||ca&&"string"===typeof ca[1]||(xa=!1,Ba="src");xa||(Da[Y]=Ba)}ja=La;La+=Y.length;if(xa){xa=ca[1];var Sa=Y.indexOf(xa),Sb=Sa+xa.length;ca[2]&&(Sb=Y.length-ca[2].length,
Sa=Sb-xa.length);Ba=Ba.substring(5);e(wa+ja,Y.substring(0,Sa),Qa,ua);e(wa+ja+Sa,xa,l(Ba,xa),ua);e(wa+ja+Sb,Y.substring(Sb),Qa,ua)}else ua.push(wa+ja,Ba)}Fa.Ej=ua};return Qa}function g(L){var X=[],la=[];L.tripleQuotedStrings?X.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):L.multiLineStrings?X.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):X.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);L.verbatimStrings&&la.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var ia=L.hashComments;ia&&(L.cStyleComments?(1<ia?X.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):X.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),la.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):
X.push(["com",/^#[^\r\n]*/,null,"#"]));L.cStyleComments&&(la.push(["com",/^\/\/[^\r\n]*/,null]),la.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));L.regexLiterals&&la.push(["lang-regex",new RegExp("^"+n+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);L=L.keywords.replace(/^\s+|\s+$/g,"");L.length&&la.push(["kwd",new RegExp("^(?:"+L.replace(/\s+/g,"|")+")\\b"),null]);X.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);la.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,
null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(X,la)}function h(L){function X(Ke){if(Ke>ua){La&&La!==Ma&&(wa.push("</span>"),La=null);!La&&Ma&&(La=Ma,wa.push('<span class="',La,'">'));var tl=a(aa(la.substring(ua,Ke))).replace(ja?Ba:Y,"$1&#160;");ja=xa.test(tl);wa.push(tl.replace(ca,sl));ua=
Ke}}var la=L.source,ia=L.Bn,ta=L.Ej,Qa=L.bk,Fa=L.Ek,wa=[],ua=0,La=null,Ma=null,Da=0,Z=0,aa=d(window.PR_TAB_WIDTH),Y=/([\r\n ]) /g,Ba=/(^| ) /gm,ca=/\r\n?|\n/g,xa=/[ \r\n]$/,ja=!0,Sa=window._pr_isIE6();Fa=Sa?Fa&&"PRE"===Fa.tagName?6===Sa?"&#160;\r\n":7===Sa?"&#160;<br />\r":8===Sa?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Qa){var Sb=[];for(Sa=0;10>Sa;++Sa)Sb[Sa]=Fa+'</li><li class="L'+Sa+'">';var Od="number"===typeof Qa?Qa-1:0;wa.push('<ol class="linenums"><li class="L',Od%10,'"');Od&&wa.push(' value="',
Od+1,'"');wa.push(">");var sl=function(){var Ke=Sb[++Od%10];return La?"</span>"+Ke+'<span class="'+La+'">':Ke}}else sl=Fa;for(;;)if(Da<ia.length&&(Z<ta.length?ia[Da]<=ta[Z]:1))X(ia[Da]),La&&(wa.push("</span>"),La=null),wa.push(ia[Da+1]),Da+=2;else if(Z<ta.length)X(ta[Z]),Ma=ta[Z+1],Z+=2;else break;X(la.length);La&&wa.push("</span>");Qa&&wa.push("</li></ol>");L.Sh=wa.join("")}function k(L,X){for(var la=X.length;0<=--la;){var ia=X[la];Ka.hasOwnProperty(ia)?"console"in window&&console.warn("cannot override language handler %s",
ia):Ka[ia]=L}}function l(L,X){L&&Ka.hasOwnProperty(L)||(L=/^\s*</.test(X)?"default-markup":"default-code");return Ka[L]}function m(L){var X=L.Dk,la=L.Tj;L.Sh=X;try{var ia=X.match(Ha);X=[];var ta=0,Qa=[];if(ia)for(var Fa=0,wa=ia.length;Fa<wa;++Fa){var ua=ia[Fa];if(1<ua.length&&"<"===ua.charAt(0)){if(!ma.test(ua))if(Aa.test(ua))X.push(ua.substring(9,ua.length-3)),ta+=ua.length-12;else if(oa.test(ua))X.push("\n"),++ta;else if(0<=ua.indexOf("nocode")&&ua.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var La=ua.match($a)[2],Ma=1;var Da=Fa+1;a:for(;Da<wa;++Da){var Z=ia[Da].match($a);if(Z&&Z[2]===La)if("/"===Z[1]){if(0===--Ma)break a}else++Ma}Da<wa?(Qa.push(ta,ia.slice(Fa,Da+1).join("")),Fa=Da):Qa.push(ta,ua)}else Qa.push(ta,ua)}else{Ma=ua;var aa=Ma.indexOf("&");if(0>aa)var Y=Ma;else{for(--aa;0<=(aa=Ma.indexOf("&#",aa+1));){var Ba=Ma.indexOf(";",aa);if(0<=Ba){var ca=Ma.substring(aa+3,Ba),xa=10;ca&&"x"===ca.charAt(0)&&(ca=ca.substring(1),
xa=16);var ja=parseInt(ca,xa);isNaN(ja)||(Ma=Ma.substring(0,aa)+String.fromCharCode(ja)+Ma.substring(Ba+1))}}Y=Ma.replace(C,"<").replace(D,">").replace(T,"'").replace(E,'"').replace(ra," ").replace(da,"&")}X.push(Y);ta+=Y.length}}var Sa=X.join("");L.source=Sa;L.tj=0;L.Bn=Qa;l(la,Sa)(L);h(L)}catch(Sb){"console"in window&&console.log(Sb&&Sb.stack?Sb.stack:Sb)}}var n=function(){for(var L="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
X="(?:^^|[+-]",la=0;la<L.length;++la)X+="|"+L[la].replace(/([^=<>:&a-z])/g,"\\$1");return X+")\\s*"}(),t=/&/g,v=/</g,w=/>/g,y=/"/g,C=/&lt;/g,D=/&gt;/g,T=/&apos;/g,E=/&quot;/g,da=/&amp;/g,ra=/&nbsp;/g,pa=/[\r\n]/g,Ga=null,Ha=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),ma=/^\x3c!--/,Aa=/^<!\[CDATA\[/,oa=/^<br\b/i,$a=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,Ab=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ka={};k(Ab,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(L,X,la){L={Dk:L,Tj:X,bk:la};m(L);return L.Sh};window.prettyPrint=function(L){function X(){for(var Ma=
window.PR_SHOULD_USE_CONTINUATION?wa.now()+250:Infinity;ua<ia.length&&wa.now()<Ma;ua++){var Da=ia[ua];if(Da.className&&0<=Da.className.indexOf("prettyprint")){var Z=Da.className.match(/\blang-(\w+)\b/);Z&&(Z=Z[1]);for(var aa=!1,Y=Da.parentNode;Y;Y=Y.parentNode)if(("pre"===Y.tagName||"code"===Y.tagName||"xmp"===Y.tagName)&&Y.className&&0<=Y.className.indexOf("prettyprint")){aa=!0;break}if(!aa){Y=Da;null===Ga&&(aa=document.createElement("PRE"),aa.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
Ga=!/</.test(aa.innerHTML));if(Ga)if(aa=Y.innerHTML,"XMP"===Y.tagName)aa=a(aa);else{if("PRE"!==Y.tagName&&pa.test(aa)){var Ba="";Y.currentStyle?Ba=Y.currentStyle.whiteSpace:window.getComputedStyle&&(Ba=window.getComputedStyle(Y,null).whiteSpace);Y=!Ba||"pre"===Ba}else Y=!0;Y||(aa=aa.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{aa=[];for(Y=Y.firstChild;Y;Y=Y.nextSibling)b(Y,aa);aa=aa.join("")}aa=aa.replace(/(?:\r\n?|\n)$/,"");Y=Da.className.match(/\blinenums\b(?::(\d+))?/);
La={Dk:aa,Tj:Z,Ek:Da,bk:Y?Y[1]&&Y[1].length?+Y[1]:!0:!1};m(La);if(Da=La.Sh)if(Z=La.Ek,"XMP"===Z.tagName){aa=document.createElement("PRE");for(Y=0;Y<Z.attributes.length;++Y)Ba=Z.attributes[Y],Ba.specified&&("class"===Ba.name.toLowerCase()?aa.className=Ba.value:aa.setAttribute(Ba.name,Ba.value));aa.innerHTML=Da;Z.parentNode.replaceChild(aa,Z)}else Z.innerHTML=Da}}}ua<ia.length?setTimeout(X,250):L&&L()}for(var la=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
ia=[],ta=0;ta<la.length;++ta)for(var Qa=0,Fa=la[ta].length;Qa<Fa;++Qa)ia.push(la[ta][Qa]);la=null;var wa=Date;wa.now||(wa={now:function(){return(new Date).getTime()}});var ua=0,La;X()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[window.PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[window.PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[window.PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[window.PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[window.PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],
[window.PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],[window.PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[window.PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[window.PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[window.PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[window.PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);
window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([],[[window.PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[window.PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\v\f\r "],[window.PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[window.PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[window.PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[window.PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[window.PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[window.PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[window.PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],
[window.PR.PR_LITERAL,/^(?:true|false|null)\b/],[window.PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[window.PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[window.PR.PR_COMMENT,/^\/\/.*/],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[window.PR.PR_STRING,/'.'/],[window.PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[window.PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[window.PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[window.PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),
["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[window.PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[window.PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[window.PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[window.PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[window.PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[window.PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[window.PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[window.PR.PR_LITERAL,
/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_]\w*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[window.PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[window.PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[window.PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);window.PR.registerLangHandler(window.PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[window.PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[window.PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[window.PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[window.PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[window.PR.PR_KEYWORD,
/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],[window.PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[window.PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[window.PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[window.PR.PR_PLAIN,
/^[$a-zA-Z_][\w$]*/],[window.PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[window.PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[window.PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[window.PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[window.PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[window.PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[window.PR.PR_PLAIN,/^[a-z_][\w-]*/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[window.PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[window.PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[window.PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[window.PR.PR_LITERAL,/^(?:true|false|nil)\b/,
null],[window.PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[window.PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[window.PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[window.PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[window.PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[window.PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[window.PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[window.PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[window.PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[window.PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[window.PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[window.PR.PR_PUNCTUATION,/^(?:\[|\])/]]),
["vb","vbs"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[window.PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[window.PR.PR_COMMENT,/^--[^\r\n]*/],[window.PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[window.PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[window.PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[window.PR.PR_LITERAL,
/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],[window.PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[window.PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[window.PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[window.PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[window.PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[window.PR.PR_PLAIN,
/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);window.PR.registerLangHandler(window.PR.createSimpleLexer([[window.PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[window.PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[window.PR.PR_TYPE,/^[&]\S+/,null,"&"],[window.PR.PR_TYPE,/^!\S*/,null,"!"],[window.PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[window.PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[window.PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[window.PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[window.PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],
[window.PR.PR_PUNCTUATION,/^-/],[window.PR.PR_KEYWORD,/^\w+:[ \r\n]/],[window.PR.PR_PLAIN,/^\w+/]]),["yaml","yml"]);var TM=window;var VM=function(a){a.C&&a.eventHandler.listen(a.C,"click",()=>void a.setAttribute("dark-code",""));a.D&&a.eventHandler.listen(a.D,"click",()=>void a.removeAttribute("dark-code"));a.h&&a.eventHandler.listen(a.h,"click",()=>void UM(a));a.o&&a.eventHandler.listen(a.o,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.CH(c,b):_ds.BH([a],b)})},UM=async function(a){var b=a.querySelector("pre:not(.devsite-copy-hide)");
if(b&&(b=[...b.childNodes],_ds.gq(document.body,b),a.v)){const c=new _ds.Bk;let d;null==(d=a.h)||d.setAttribute("aria-label","Code sample copied to clipboard");_ds.zk(a.eventHandler,a.v,"transitionend",()=>{c.g()});await c.promise;_ds.zk(a.eventHandler,a.v,"transitionend",()=>{let e;null==(e=a.h)||e.setAttribute("aria-label",a.G)})}},WM=class extends _ds.G{constructor(){super(["devsite-snackbar"]);this.v=this.D=this.o=this.C=this.h=this.g=null;this.J=!1;this.G="";this.eventHandler=new _ds.I;this.H=
new _ds.Bk;this.F=new _ds.jm;this.K=new _ds.XD(_ds.aE(_ds.$D()));_ds.Og(this,(0,_ds.u)`no-toggle`)}static get observedAttributes(){return["dark-code"]}whenReady(){return this.H.promise}async connectedCallback(){var a=await _ds.x();if(!this.J){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",
""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.G=c?`${"Copy code sample"}: ${c}`:"Copy code sample";b.classList.contains("devsite-disable-code-toggle")&&(_ds.F(this,"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",
""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}this.prettyPrint();this.J=!0}if((d=this.querySelector(".devsite-dark-code-default"))||this.F.get("pref_dark-code"))this.setAttribute("dark-code",""),d&&d.classList.remove("devsite-dark-code-default");
this.H.g();try{await a.intersectionEnterForElement(this)}catch(g){if("IntersectionObserver not supported"!==g.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.g=a;else{this.g=_ds.O(OM);if(this.hasAttribute("scope")){this.o=_ds.O(SM,{label:"Open code sample in JSFiddle"});(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.o.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||this.getAttribute("jsfiddle-title")}`);var e;null==
(e=this.g)||e.appendChild(this.o)}if(!this.hasAttribute("no-toggle")){this.C=_ds.O(PM,{label:"Dark code theme"});var f;null==(f=this.g)||f.appendChild(this.C);this.D=_ds.O(QM,{label:"Light code theme"});let g;null==(g=this.g)||g.appendChild(this.D)}if(!this.hasAttribute("no-copy")){e=this.getAttribute("data-copy-event-label");f="Click To Copy";e&&(f+=`: ${e}`);this.h=_ds.O(RM,{label:this.G,dn:f});let g;null==(g=this.g)||g.appendChild(this.h)}this.prepend(this.g)}VM(this);this.v=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.x()).unregisterIntersectionForElement(this);
this.g&&this.removeChild(this.g);_ds.J(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");var b=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;let d;a=c.innerHTML;b=null!=(d=b)?d:"";a=a.replace(/(&#39;)/g,"'");a=TM.prettyPrintOne(a,b,void 0);_ds.Fc(c,this.K.g(a));c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===
a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.F.set("pref_dark-code","1");await _ds.jj();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.F.remove("pref_dark-code");await _ds.jj();e=[...document.querySelectorAll("devsite-code[dark-code]")];for(d of e)d.removeAttribute("dark-code")}}};WM.prototype.attributeChangedCallback=WM.prototype.attributeChangedCallback;
WM.prototype.disconnectedCallback=WM.prototype.disconnectedCallback;WM.prototype.connectedCallback=WM.prototype.connectedCallback;WM.prototype.whenReady=WM.prototype.whenReady;try{window.customElements.define("devsite-code",WM)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
